services:
  postgres:
    image: postgres:16
    container_name: sqlxo-db
    restart: no
    environment:
      POSTGRES_HOSTADDR: "localhost"
      POSTGRES_DB: "sqlxo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - magazin-network
    ports:
      - "2345:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  magazin-network:

volumes:
  postgres-data:
